---
- name: Playbook Control Lab
  hosts: webservers
  vars_files: vars.yml
  tasks:
    #Fail Fast Message. The remote system have to meet requirement about minimum of ram and os distribution
    - name: Show Failed System Requirements Message
      fail:
        msg: "The {{ inventory_hostname }} does not meet minimum requirements"
      when: >
        ansible_memtotal_mb < min_ram_mb or 
        ansible_distribution != "RedHat"
    #Install all Packages
    - name: Ensure required packages are present
      yum:
        name: "{{ item }}"
        state: latest
      loop: "{{ packages }}"

    #Enable and start services
    - name: Enable and start services {{ services }}
      service:
        name: "{{ item }}"
        state: started
      loop: "{{ services }}"

    #Block of config tasks
    - name: Block of Setting up SSL cert directory and config files.
      block:
        - name: Ensure the {{ ssl_cert_dir }} is available on the remote host
          file:
            path: "{{ ssl_cert_dir }}"
            state: directory

        - name: Copy files config
          copy:
            src: "{{ item.src }}"
            dest: "{{ item.dest }}"
          loop: "{{ web_config_files }}"
          notify: Restart web service

      rescue:
        - name: configuration Error Message
          debug:
            msg: "One or more of the configuration changes failed, but the web service is still active"

    #Configure the firewall
    - name: Allow http on firewall
      firewalld:
        service: "{{ item }}"
        state: enabled
        permanent: true
        immediate: true
      loop:
        - http
        - https

  #Add handlers
  handlers:
    - name: Restart web service
      service:
        name: "{{ web_service }}"
        state: restarted

