---
# tasks file for myvhost
- name: Ensure the httpd is installed
  yum:
    name: httpd
    state: latest

- name: Ensure the httpd is started and enabled
  service:
     name: httpd
     state: started
     enabled: true

- name: Ensure the vhost file is installed
  template:
    src: vhost.conf.j2
    dest: /etc/httpd/conf.d/vhost.conf
    owner: root
    group: root
    mode: 0644
  notify: 
    - restart httpd
